### PR TITLE
Contact us modal

### PR DESCRIPTION
**Pull request by erwilliams64**
wooo, still learning. Hopefully this contact-us modal doesnt affect anyone else. Please let me know if I am doing anything wrong!

### CODE REVIEW

**Review by schromya — CHANGES_REQUESTED** [review]
Yooo looks good- congrats on your first PR! The only request I have is that you add a comment block to your added functions in JSDoc formatting.

```
Ex/
/**
 * Calculates the sum of two numbers.
 *
 * @param {number} a - The first number.
 * @param {number} b - The second number.
 * @returns {number} The sum of the two numbers.
 */
function add(a, b) {
    return a + b;
}
```

Also since this is our second modal, I was thinking we could make a modal template component that lets you pass in the fields, submit action, etc. But that can come later.

**Comment by erwilliams64** [comment]
Agree on making a modal template component. Jason recommends Hook Form (https://react-hook-form.com/) and uses Formik on some of his work, but ultimately, we may want to make a new file of all the form components we want to call (submitForm, handleClose, etc).

**Comment by erwilliams64** [comment]
Is this waiting on anything from me?

**Review by jaren-ramirez — APPROVED** [review]
Looks really good

**Review by schromya — APPROVED** [review]

**Comment by erwilliams64** [comment]
Thanks!

**Pull request closed without merging**
